repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        files: \.py$
      - id: trailing-whitespace
        files: \.py$
      - id: check-ast
        files: \.py$
      - id: check-builtin-literals
        files: \.py$
      - id: check-docstring-first
        files: \.py$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-symlinks
      - id: fix-byte-order-marker
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-format
        args: [ "--config=ruff.toml" ]
      - id: ruff-check
        args: [ "--fix", "--config=ruff.toml" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - --follow-imports=silent
          - --ignore-missing-imports
          - --show-error-codes
          - --explicit-package-bases
          - --no-implicit-reexport
          - --warn-unused-ignores
          - --warn-redundant-casts
          - --disable-error-code=var-annotated

          # - --disallow-untyped-defs
          # - --disallow-incomplete-defs
          # - --disallow-untyped-calls
          # - --strict
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-simplejson
          - types-pytz
          - types-ujson
          - types-tensorflow
          - types-PyYAML
          - pandas-stubs
          - scipy-stubs
          - types-psycopg2
          - types-tqdm
          - types-waitress
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        args: [ --ignore, DL3025, --ignore, DL3018 ]
